print(" my name is abbas ali ")
print(" my name is abbas ali ")
print(" my name is abbas ali ")
print(" my name is abbas ali ")
print(" my name is abbas ali ")
print(" my name is abbas ali ")
print("my name is abbas ali ")
print(" my name ia abbas ali ")
print(" my name is abbas ali ")
print(" my name is abbas ali ")
